spring:
  application:
    name: library-system
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:lib-system
    username: SA
    password: Test@12
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

